title: ABCD
email: cndrhkr33epdlxj1@gmail.com
description: AI BigData Computing Deeplearning
author: ABCD
baseurl: ""
url: "https://cbshabcd.github.io"
language: 'ko-kr'

destination: ./output

# Social Profiles
twitter_username:
github_username: CBSHABCD
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
# paginate: 5
# paginate_path: "/seminar/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-paginate-v2
  # - jekyll-paginate

pagination:
  enabled: true
  per_page: 5
  limit: 0
  sort_field: "date"
  sort_reverse: true
  title: "title"
